# -*- coding: utf-8 -*-
"""041225burak_sensetech_High_Precision_Weather_Forecasting_with_Prophet (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qcc7ojeeCDsYJaGhhwnnrxBRockTqqbB

## Hybrid Prediction
"""

!pip install prophet statsmodels xgboost scikit-learn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from prophet import Prophet
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.ensemble import RandomForestRegressor, StackingRegressor
from sklearn.linear_model import Ridge
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

if not hasattr(np, "float_"):
    np.float_ = np.float64

plt.rcParams["figure.figsize"] = (14, 6)
plt.style.use('seaborn-v0_8-whitegrid')
print("✅ Kütüphaneler yüklendi!")

df = pd.read_csv("cleaned_weather.csv")
df['date'] = pd.to_datetime(df['date'])

print(f"Toplam satır: {len(df):,}")
print(f"Tarih aralığı: {df['date'].min()} - {df['date'].max()}")
print(f"Kolonlar: {df.columns.tolist()}")
df.head()

# Saatlik ortalama
df_hourly = df.set_index('date').resample('H').mean().reset_index()

# Temel zaman özellikleri
df_hourly['hour'] = df_hourly['date'].dt.hour
df_hourly['day'] = df_hourly['date'].dt.day
df_hourly['month'] = df_hourly['date'].dt.month
df_hourly['dayofweek'] = df_hourly['date'].dt.dayofweek
df_hourly['dayofyear'] = df_hourly['date'].dt.dayofyear

# Döngüsel özellikler
df_hourly['hour_sin'] = np.sin(2 * np.pi * df_hourly['hour'] / 24)
df_hourly['hour_cos'] = np.cos(2 * np.pi * df_hourly['hour'] / 24)
df_hourly['month_sin'] = np.sin(2 * np.pi * df_hourly['month'] / 12)
df_hourly['month_cos'] = np.cos(2 * np.pi * df_hourly['month'] / 12)

# Rüzgar yönü sin/cos
df_hourly['wd_sin'] = np.sin(np.deg2rad(df_hourly['wd']))
df_hourly['wd_cos'] = np.cos(np.deg2rad(df_hourly['wd']))

# ⭐ LAG FEATURES - ÇOK ÖNEMLİ!
TARGET = 'T'
for lag in [1, 2, 3, 6, 12, 24]:
    df_hourly[f'T_lag_{lag}'] = df_hourly[TARGET].shift(lag)

# Rolling features
df_hourly['T_rolling_6h_mean'] = df_hourly[TARGET].rolling(window=6).mean()
df_hourly['T_rolling_24h_mean'] = df_hourly[TARGET].rolling(window=24).mean()
df_hourly['T_rolling_6h_std'] = df_hourly[TARGET].rolling(window=6).std()

# NaN'ları temizle (lag ve rolling'den dolayı)
df_hourly = df_hourly.dropna().reset_index(drop=True)

print(f"Saatlik veri (temizlik sonrası): {len(df_hourly):,} satır")
print(f"Tarih aralığı: {df_hourly['date'].min()} - {df_hourly['date'].max()}")

TEST_DAYS = 7
TEST_SIZE = TEST_DAYS * 24

train = df_hourly[:-TEST_SIZE].copy()
test = df_hourly[-TEST_SIZE:].copy()

print("=" * 60)
print(f"Train: {len(train):,} satır ({train['date'].min().date()} - {train['date'].max().date()})")
print(f"Test: {len(test):,} satır ({test['date'].min().date()} - {test['date'].max().date()})")
print("=" * 60)

# Görselleştirme
plt.figure(figsize=(14, 5))
plt.plot(train['date'], train[TARGET], label='Train', linewidth=0.7)
plt.plot(test['date'], test[TARGET], label='Test', linewidth=1.5, color='red')
plt.axvline(x=test['date'].iloc[0], color='black', linestyle='--')
plt.title('Train/Test Split', fontsize=14, fontweight='bold')
plt.legend()
plt.show()

def calculate_metrics(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mse = mean_squared_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    # MAPE - sıfıra yakın değerleri filtrele
    mask = np.abs(y_true) > 1.0  # Sadece |T| > 1°C olanlar
    if mask.sum() > 0:
        mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100
    else:
        mape = np.nan

    return {
        'Model': model_name,
        'MAE': round(mae, 4),
        'RMSE': round(rmse, 4),
        'MSE': round(mse, 4),
        'R²': round(r2, 4),
        'MAPE (%)': round(mape, 2) if not np.isnan(mape) else 'N/A'
    }

all_results = []
all_predictions = {}
test_dates = test['date'].values
y_test_actual = test[TARGET].values

print("✅ Hazırlıklar tamamlandı!")

print("=" * 60)
print("1. PROPHET MODELİ")
print("=" * 60)

# Prophet veri hazırlığı
prophet_train = train[['date', TARGET]].rename(columns={'date': 'ds', TARGET: 'y'})

# Model
prophet_model = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=True,
    daily_seasonality=True,
    seasonality_mode='additive',
    changepoint_prior_scale=0.05
)

prophet_model.fit(prophet_train)

# Future dataframe
future = pd.DataFrame({'ds': test['date']})
prophet_forecast = prophet_model.predict(future)
prophet_pred = prophet_forecast['yhat'].values

# Metrik
prophet_metrics = calculate_metrics(y_test_actual, prophet_pred, 'Prophet')
all_results.append(prophet_metrics)
all_predictions['Prophet'] = prophet_pred

print(f"\n📊 Prophet: MAE={prophet_metrics['MAE']}, RMSE={prophet_metrics['RMSE']}, R²={prophet_metrics['R²']}")

print("=" * 60)
print("2. SARIMA MODELİ")
print("=" * 60)

# Son 1000 saat ile eğit (hız için)
sarima_data = train[TARGET].iloc[-1000:].values

print("SARIMA eğitiliyor...")
sarima_model = SARIMAX(
    sarima_data,
    order=(1, 1, 1),
    seasonal_order=(1, 0, 1, 24),
    enforce_stationarity=False,
    enforce_invertibility=False
)
sarima_result = sarima_model.fit(disp=False)

# Tahmin
sarima_pred = sarima_result.forecast(steps=len(test))

# Metrik
sarima_metrics = calculate_metrics(y_test_actual, sarima_pred, 'SARIMA')
all_results.append(sarima_metrics)
all_predictions['SARIMA'] = sarima_pred

print(f"\n📊 SARIMA: MAE={sarima_metrics['MAE']}, RMSE={sarima_metrics['RMSE']}, R²={sarima_metrics['R²']}")

print("=" * 60)
print("ML MODELLERİ İÇİN FEATURE HAZIRLIĞI")
print("=" * 60)

# ⚠️ Leak feature'ları ÇIKAR, Lag feature'ları EKLE
FEATURES = [
    # Zaman özellikleri
    'hour', 'day', 'month', 'dayofweek', 'dayofyear',
    'hour_sin', 'hour_cos', 'month_sin', 'month_cos',

    # Meteorolojik (leak olmayan)
    'p', 'rh', 'sh', 'rho', 'wv', 'wd_sin', 'wd_cos',
    'rain', 'SWDR', 'PAR',

    # ⭐ LAG FEATURES - Kritik!
    'T_lag_1', 'T_lag_2', 'T_lag_3', 'T_lag_6', 'T_lag_12', 'T_lag_24',
    'T_rolling_6h_mean', 'T_rolling_24h_mean', 'T_rolling_6h_std'
]

available_features = [f for f in FEATURES if f in train.columns]
print(f"Feature sayısı: {len(available_features)}")

X_train = train[available_features].values
y_train = train[TARGET].values
X_test = test[available_features].values
y_test = test[TARGET].values

print(f"X_train: {X_train.shape}, X_test: {X_test.shape}")

print("=" * 60)
print("3. RANDOM FOREST MODELİ")
print("=" * 60)

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)

print("Eğitiliyor...")
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

rf_metrics = calculate_metrics(y_test, rf_pred, 'Random Forest')
all_results.append(rf_metrics)
all_predictions['Random Forest'] = rf_pred

print(f"\n📊 Random Forest: MAE={rf_metrics['MAE']}, RMSE={rf_metrics['RMSE']}, R²={rf_metrics['R²']}")

# Feature importance
feat_imp = pd.DataFrame({'Feature': available_features, 'Importance': rf_model.feature_importances_})
print("\n🔝 Top 5 Features:")
print(feat_imp.sort_values('Importance', ascending=False).head().to_string(index=False))

print("=" * 60)
print("4. XGBOOST MODELİ")
print("=" * 60)

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    verbosity=0
)

print("Eğitiliyor...")
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

xgb_metrics = calculate_metrics(y_test, xgb_pred, 'XGBoost')
all_results.append(xgb_metrics)
all_predictions['XGBoost'] = xgb_pred

print(f"\n📊 XGBoost: MAE={xgb_metrics['MAE']}, RMSE={xgb_metrics['RMSE']}, R²={xgb_metrics['R²']}")

print("=" * 60)
print("5. HİBRİT MODEL (Stacking)")
print("=" * 60)

hybrid_model = StackingRegressor(
    estimators=[
        ('rf', RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)),
        ('xgb', XGBRegressor(n_estimators=150, max_depth=6, learning_rate=0.05, random_state=42, verbosity=0))
    ],
    final_estimator=Ridge(alpha=1.0),
    cv=5,
    n_jobs=-1
)

print("Eğitiliyor...")
hybrid_model.fit(X_train, y_train)
hybrid_pred = hybrid_model.predict(X_test)

hybrid_metrics = calculate_metrics(y_test, hybrid_pred, 'Hybrid (Stacking)')
all_results.append(hybrid_metrics)
all_predictions['Hybrid'] = hybrid_pred

print(f"\n📊 Hybrid: MAE={hybrid_metrics['MAE']}, RMSE={hybrid_metrics['RMSE']}, R²={hybrid_metrics['R²']}")

print("=" * 70)
print("📊 TÜM MODELLER - KARŞILAŞTIRMA")
print("=" * 70)

results_df = pd.DataFrame(all_results)
results_df = results_df.drop_duplicates(subset=['Model'])
results_df = results_df.sort_values('RMSE').reset_index(drop=True)

print(results_df.to_string(index=False))

best = results_df.iloc[0]
print(f"\n🏆 En İyi Model: {best['Model']}")
print(f"   MAE: {best['MAE']} °C")
print(f"   RMSE: {best['RMSE']} °C")
print(f"   R²: {best['R²']}")

fig, axes = plt.subplots(2, 2, figsize=(16, 12), dpi=300)

# All predictions
ax1 = axes[0, 0]
ax1.plot(test_dates, y_test_actual, 'k-', label='Actual', linewidth=2)
colors = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12', '#9b59b6']
for i, (name, pred) in enumerate(all_predictions.items()):
    ax1.plot(test_dates, pred, label=name, alpha=0.7, linewidth=1.5)
ax1.set_title('All Model Predictions', fontsize=12, fontweight='bold')
ax1.legend()
ax1.set_ylabel('Temperature (°C)')

# MAE comparison
ax2 = axes[0, 1]
ax2.barh(results_df['Model'], results_df['MAE'], color=colors[:len(results_df)])
ax2.set_title('MAE Comparison', fontsize=12, fontweight='bold')
ax2.set_xlabel('MAE (°C)')

# R² comparison
ax3 = axes[1, 0]
ax3.barh(results_df['Model'], results_df['R²'], color=colors[:len(results_df)])
ax3.set_title('R² Comparison', fontsize=12, fontweight='bold')
ax3.set_xlabel('R²')
ax3.axvline(x=0, color='red', linestyle='--')

# Best model detail
best_name = results_df.iloc[0]['Model']
best_pred = all_predictions.get(best_name, list(all_predictions.values())[0])
ax4 = axes[1, 1]
ax4.plot(test_dates, y_test_actual, 'b-', label='Actual', linewidth=2)
ax4.plot(test_dates, best_pred, 'r--', label=f'{best_name} Prediction', linewidth=2)
ax4.fill_between(test_dates, y_test_actual, best_pred, alpha=0.3, color='gray')
ax4.set_title(f'Best Model: {best_name}', fontsize=12, fontweight='bold')
ax4.legend()
ax4.set_ylabel('Temperature (°C)')

plt.tight_layout()
plt.show()

print("=" * 70)
print("📋 FİNAL RAPOR")
print("=" * 70)

print(f"""
📅 Veri Bilgileri:
   Toplam: {len(df):,} satır (10 dakikalık)
   Saatlik: {len(df_hourly):,} satır
   Test: Son {TEST_DAYS} gün ({TEST_SIZE} saat)

🎯 Hedef: Sıcaklık (T) tahmini

📊 Model Performansları:
""")
print(results_df.to_string(index=False))

print(f"""

🏆 En İyi Model: {results_df.iloc[0]['Model']}

💡 Değerlendirme:
   • Lag features (geçmiş sıcaklık değerleri) en önemli özellikler
   • ML modelleri zaman serisi modellerinden daha iyi performans gösterdi
   • Hibrit yaklaşım modellerin güçlü yönlerini birleştiriyor
""")

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

best_models = ['Hybrid', 'Random Forest', 'XGBoost']
colors = ['#2ecc71', '#9b59b6', '#f39c12']

for idx, model in enumerate(best_models):
    pred = all_predictions[model]
    ax = axes[idx]

    ax.scatter(y_test_actual, pred, alpha=0.6, color=colors[idx], s=30)

    # Mükemmel tahmin çizgisi
    min_val, max_val = min(y_test_actual.min(), pred.min()), max(y_test_actual.max(), pred.max())
    ax.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='Mükemmel Tahmin')

    # R² göster
    r2 = r2_score(y_test_actual, pred)
    ax.text(0.05, 0.95, f'R² = {r2:.4f}', transform=ax.transAxes, fontsize=12,
            fontweight='bold', verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    ax.set_xlabel('Gerçek Sıcaklık (°C)', fontsize=11)
    ax.set_ylabel('Tahmin (°C)', fontsize=11)
    ax.set_title(model, fontsize=12, fontweight='bold')
    ax.legend()

plt.suptitle('Gerçek vs Tahmin Karşılaştırması', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

best_models = ['Hybrid', 'Random Forest', 'XGBoost']
colors = ['#2ecc71', '#9b59b6', '#f39c12']

for idx, model in enumerate(best_models):
    pred = all_predictions[model]
    errors = y_test_actual - pred

    ax = axes[idx]
    ax.hist(errors, bins=25, color=colors[idx], edgecolor='black', alpha=0.7)
    ax.axvline(x=0, color='red', linestyle='--', linewidth=2)
    ax.axvline(x=np.mean(errors), color='blue', linestyle=':', linewidth=2,
               label=f'Ort: {np.mean(errors):.3f}°C')

    ax.set_xlabel('Tahmin Hatası (°C)', fontsize=11)
    ax.set_ylabel('Frekans', fontsize=11)
    ax.set_title(f'{model} - Hata Dağılımı', fontsize=12, fontweight='bold')
    ax.legend()

plt.tight_layout()
plt.show()

# Test setine tahminleri ekle
test_analysis = test[['date', 'hour', TARGET]].copy()
test_analysis['Hybrid_pred'] = all_predictions['Hybrid']
test_analysis['RF_pred'] = all_predictions['Random Forest']
test_analysis['XGB_pred'] = all_predictions['XGBoost']

# Saatlik MAE hesapla
hourly_mae = test_analysis.groupby('hour').apply(
    lambda x: pd.Series({
        'Hybrid': np.abs(x[TARGET] - x['Hybrid_pred']).mean(),
        'Random Forest': np.abs(x[TARGET] - x['RF_pred']).mean(),
        'XGBoost': np.abs(x[TARGET] - x['XGB_pred']).mean()
    })
)

# Görselleştir
fig, ax = plt.subplots(figsize=(12, 5))
hourly_mae.plot(kind='bar', ax=ax, width=0.8, alpha=0.8)
ax.set_xlabel('Saat', fontsize=11)
ax.set_ylabel('MAE (°C)', fontsize=11)
ax.set_title('Saatlik Ortalama Mutlak Hata', fontsize=14, fontweight='bold')
ax.legend(title='Model')
ax.set_xticklabels(range(24), rotation=0)
plt.tight_layout()
plt.show()

print("\n📊 En yüksek hata saatleri (Hybrid):")
print(hourly_mae['Hybrid'].sort_values(ascending=False).head())

# RF ve XGBoost feature importance
rf_imp = pd.DataFrame({'Feature': available_features, 'RF': rf_model.feature_importances_})
xgb_imp = pd.DataFrame({'Feature': available_features, 'XGBoost': xgb_model.feature_importances_})

importance_df = rf_imp.merge(xgb_imp, on='Feature')
importance_df['Average'] = (importance_df['RF'] + importance_df['XGBoost']) / 2
importance_df = importance_df.sort_values('Average', ascending=False)

# Top 15 feature
fig, ax = plt.subplots(figsize=(10, 8))
top_15 = importance_df.head(15)

x = np.arange(len(top_15))
width = 0.35

bars1 = ax.barh(x - width/2, top_15['RF'], width, label='Random Forest', color='#9b59b6', alpha=0.8)
bars2 = ax.barh(x + width/2, top_15['XGBoost'], width, label='XGBoost', color='#f39c12', alpha=0.8)

ax.set_yticks(x)
ax.set_yticklabels(top_15['Feature'])
ax.invert_yaxis()
ax.set_xlabel('Importance', fontsize=11)
ax.set_title('Top 15 Feature Importance', fontsize=14, fontweight='bold')
ax.legend()

plt.tight_layout()
plt.show()

print("\n🔝 En Önemli 5 Feature:")
print(importance_df[['Feature', 'Average']].head().to_string(index=False))

# Model karşılaştırma tablosu
results_df.to_csv('model_comparison_results.csv', index=False)

# Tahminler
predictions_df = pd.DataFrame({
    'date': test_dates,
    'actual': y_test_actual,
    **all_predictions
})
predictions_df.to_csv('all_model_predictions.csv', index=False)

# Feature importance
importance_df.to_csv('feature_importance.csv', index=False)

print("✅ Dosyalar kaydedildi:")
print("   • model_comparison_results.csv")
print("   • all_model_predictions.csv")
print("   • feature_importance.csv")

print("=" * 70)
print("📝 AKADEMİK ÖZET - HAVA DURUMU TAHMİN MODELLERİ")
print("=" * 70)

print("""
AMAÇ:
Saatlik sıcaklık (T) tahmini için farklı makine öğrenmesi ve
zaman serisi modellerinin karşılaştırmalı analizi.

VERİ SETİ:
- Kaynak: 10 dakikalık meteorolojik ölçümler
- Dönem: 2020-01-01 - 2020-12-31
- Örneklem: 52,696 gözlem → 8,736 saatlik ortalama
- Test periyodu: Son 7 gün (168 saat)

MODELLER:
1. Prophet (Facebook) - Aditif mevsimsellik modeli
2. SARIMA (1,1,1)(1,0,1,24) - Klasik zaman serisi
3. Random Forest - Ensemble ağaç modeli
4. XGBoost - Gradient boosting
5. Hybrid Stacking - RF + XGBoost + Ridge meta-learner

ÖZELLİKLER:
- Zaman özellikleri: saat, gün, ay, döngüsel (sin/cos)
- Meteorolojik: basınç, nem, rüzgar, radyasyon
- Lag features: T(t-1), T(t-6), T(t-24) vb.
- Rolling: 6h ve 24h hareketli ortalama/std

SONUÇLAR:
""")

print(results_df[['Model', 'MAE', 'RMSE', 'R²']].to_string(index=False))

print(f"""

BULGULAR:
- En iyi model: Hybrid Stacking (R² = 0.949, MAE = 0.25°C)
- Lag features model performansını dramatik şekilde artırdı
- ML modelleri klasik zaman serisi modellerinden üstün
- Prophet ve SARIMA 7 günlük horizonda yetersiz kaldı

ÖNERİLER:
- Kısa vadeli tahmin (1-24 saat): Hybrid veya RF
- Feature engineering kritik öneme sahip
- Ensemble yaklaşımlar tek modellere göre daha robust
""")
print("=" * 70)

# Önce kurulum
!pip install catboost -q

from catboost import CatBoostRegressor

print("=" * 60)
print("5. CATBOOST MODELİ")
print("=" * 60)

catboost_model = CatBoostRegressor(
    iterations=500,
    depth=8,
    learning_rate=0.05,
    l2_leaf_reg=3,
    random_seed=42,
    verbose=False
)

print("CatBoost eğitiliyor...")
catboost_model.fit(X_train, y_train)
catboost_pred = catboost_model.predict(X_test)

# Metrik
catboost_metrics = calculate_metrics(y_test, catboost_pred, 'CatBoost')
all_results.append(catboost_metrics)
all_predictions['CatBoost'] = catboost_pred

print(f"\n📊 CatBoost: MAE={catboost_metrics['MAE']}, RMSE={catboost_metrics['RMSE']}, R²={catboost_metrics['R²']}")

# Feature Importance
catboost_importance = pd.DataFrame({
    'Feature': available_features,
    'Importance': catboost_model.feature_importances_
}).sort_values('Importance', ascending=False)

print("\n🔝 Top 5 Features:")
print(catboost_importance.head().to_string(index=False))

from catboost import CatBoostRegressor

print("=" * 60)
print("6. HİBRİT MODEL (Stacking - RF + XGB + CatBoost)")
print("=" * 60)

hybrid_model = StackingRegressor(
    estimators=[
        ('rf', RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)),
        ('xgb', XGBRegressor(n_estimators=150, max_depth=6, learning_rate=0.05, random_state=42, verbosity=0)),
        ('catboost', CatBoostRegressor(iterations=200, depth=6, learning_rate=0.05, random_seed=42, verbose=False))
    ],
    final_estimator=Ridge(alpha=1.0),
    cv=5,
    n_jobs=-1
)

print("Hibrit model eğitiliyor...")
hybrid_model.fit(X_train, y_train)
hybrid_pred = hybrid_model.predict(X_test)

# Eski Hybrid sonucunu güncelle
all_results = [r for r in all_results if r['Model'] != 'Hybrid (Stacking)']
all_predictions.pop('Hybrid', None)

hybrid_metrics = calculate_metrics(y_test, hybrid_pred, 'Hybrid (RF+XGB+Cat)')
all_results.append(hybrid_metrics)
all_predictions['Hybrid'] = hybrid_pred

print(f"\n📊 Hybrid: MAE={hybrid_metrics['MAE']}, RMSE={hybrid_metrics['RMSE']}, R²={hybrid_metrics['R²']}")

print("=" * 70)
print("📊 TÜM MODELLER - KARŞILAŞTIRMA (CatBoost Dahil)")
print("=" * 70)

results_df = pd.DataFrame(all_results)
results_df = results_df.drop_duplicates(subset=['Model'])
results_df = results_df.sort_values('RMSE').reset_index(drop=True)

print(results_df.to_string(index=False))

best = results_df.iloc[0]
print(f"\n🏆 En İyi Model: {best['Model']}")
print(f"   MAE: {best['MAE']} °C")
print(f"   RMSE: {best['RMSE']} °C")
print(f"   R²: {best['R²']}")

fig, axes = plt.subplots(2, 2, figsize=(16, 12), dpi=600)

# 1. All ML model predictions
ax1 = axes[0, 0]
ax1.plot(test_dates, y_test_actual, 'k-', label='Actual', linewidth=2.5)
ml_models = ['Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']
colors = ['#9b59b6', '#f39c12', '#1abc9c', '#e74c3c']
for model, color in zip(ml_models, colors):
    if model in all_predictions:
        ax1.plot(test_dates, all_predictions[model], label=model, alpha=0.7, linewidth=1.5, color=color)
ax1.set_title('ML Model Predictions', fontsize=12, fontweight='bold')
ax1.set_ylabel('Temperature (°C)')
ax1.legend()

# 2. RMSE Comparison
ax2 = axes[0, 1]
ml_results = results_df[~results_df['Model'].isin(['Prophet', 'SARIMA'])]
colors_bar = ['#2ecc71', '#9b59b6', '#f39c12', '#1abc9c', '#e74c3c']
ax2.barh(ml_results['Model'], ml_results['RMSE'], color=colors_bar[:len(ml_results)])
ax2.set_title('RMSE Comparison (ML Models)', fontsize=12, fontweight='bold')
ax2.set_xlabel('RMSE (°C)')
for i, v in enumerate(ml_results['RMSE']):
    ax2.text(v + 0.01, i, f'{v:.4f}', va='center', fontsize=10)

# 3. R² Comparison
ax3 = axes[1, 0]
ax3.barh(ml_results['Model'], ml_results['R²'], color=colors_bar[:len(ml_results)])
ax3.set_title('R² Comparison (ML Models)', fontsize=12, fontweight='bold')
ax3.set_xlabel('R²')
for i, v in enumerate(ml_results['R²']):
    ax3.text(v + 0.005, i, f'{v:.4f}', va='center', fontsize=10)

# 4. MAE Comparison
ax4 = axes[1, 1]
ax4.barh(ml_results['Model'], ml_results['MAE'], color=colors_bar[:len(ml_results)])
ax4.set_title('MAE Comparison (ML Models)', fontsize=12, fontweight='bold')
ax4.set_xlabel('MAE (°C)')
for i, v in enumerate(ml_results['MAE']):
    ax4.text(v + 0.01, i, f'{v:.4f}', va='center', fontsize=10)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(12, 10), dpi=600)
axes = axes.flatten()

models = ['Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']
colors = ['#9b59b6', '#f39c12', '#1abc9c', '#e74c3c']

for idx, (model, color) in enumerate(zip(models, colors)):
    if model in all_predictions:
        pred = all_predictions[model]
        ax = axes[idx]

        ax.scatter(y_test_actual, pred, alpha=0.6, color=color, s=30)

        min_val = min(y_test_actual.min(), pred.min())
        max_val = max(y_test_actual.max(), pred.max())
        ax.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2)

        r2 = r2_score(y_test_actual, pred)
        mae = mean_absolute_error(y_test_actual, pred)
        ax.text(0.05, 0.95, f'R² = {r2:.4f}\nMAE = {mae:.4f}°C',
                transform=ax.transAxes, fontsize=11, fontweight='bold',
                verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

        ax.set_xlabel('Actual (°C)')
        ax.set_ylabel('Predicted (°C)')
        ax.set_title(model, fontsize=12, fontweight='bold')

plt.suptitle('Actual vs Predicted - ML Models', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# All models' feature importance
importance_combined = pd.DataFrame({'Feature': available_features})
importance_combined['RF'] = rf_model.feature_importances_
importance_combined['XGBoost'] = xgb_model.feature_importances_
importance_combined['CatBoost'] = catboost_model.feature_importances_
importance_combined['Average'] = importance_combined[['RF', 'XGBoost', 'CatBoost']].mean(axis=1)
importance_combined = importance_combined.sort_values('Average', ascending=False)

# Visualization
fig, ax = plt.subplots(figsize=(12, 10), dpi=600)
top_15 = importance_combined.head(15)

x = np.arange(len(top_15))
width = 0.25

ax.barh(x - width, top_15['RF'], width, label='Random Forest', color='#9b59b6', alpha=0.8)
ax.barh(x, top_15['XGBoost'], width, label='XGBoost', color='#f39c12', alpha=0.8)
ax.barh(x + width, top_15['CatBoost'], width, label='CatBoost', color='#1abc9c', alpha=0.8)

ax.set_yticks(x)
ax.set_yticklabels(top_15['Feature'])
ax.invert_yaxis()
ax.set_xlabel('Importance', fontsize=11)
ax.set_title('Feature Importance Comparison (Top 15)', fontsize=14, fontweight='bold')
ax.legend()

plt.tight_layout()
plt.show()

print("\n🔝 Top 10 Most Important Features (Average):")
print(importance_combined[['Feature', 'Average']].head(10).to_string(index=False))

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
from scipy import stats
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd
import numpy as np

# Akademik stil ayarları
plt.rcParams.update({
    'font.size': 11,
    'font.family': 'serif',
    'axes.labelsize': 12,
    'axes.titlesize': 13,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'legend.fontsize': 10,
    'figure.titlesize': 14,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'axes.grid': True,
    'grid.alpha': 0.3
})

# Renk paleti (akademik ve tutarlı)
COLORS = {
    'Prophet': '#E74C3C',
    'SARIMA': '#3498DB',
    'Random Forest': '#9B59B6',
    'XGBoost': '#F39C12',
    'CatBoost': '#1ABC9C',
    'Hybrid': '#2C3E50',
    'Actual': '#000000'
}

print("✅ Akademik görselleştirme ayarları yüklendi!")

print("=" * 70)
print("TABLO 1: VERİ SETİ TANIMLAYICI İSTATİSTİKLERİ")
print("=" * 70)

# Ana meteorolojik değişkenler
main_vars = ['T', 'p', 'rh', 'wv', 'rain', 'SWDR', 'PAR']
available_vars = [v for v in main_vars if v in df_hourly.columns]

# İstatistikler
stats_df = df_hourly[available_vars].describe().T
stats_df['Değişken'] = stats_df.index
stats_df = stats_df[['Değişken', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']]
stats_df.columns = ['Değişken', 'N', 'Ortalama', 'Std. Sapma', 'Min', 'Q1', 'Medyan', 'Q3', 'Max']

# Yuvarlama
for col in ['Ortalama', 'Std. Sapma', 'Min', 'Q1', 'Medyan', 'Q3', 'Max']:
    stats_df[col] = stats_df[col].round(2)
stats_df['N'] = stats_df['N'].astype(int)

# Değişken açıklamaları
var_descriptions = {
    'T': 'Sıcaklık (°C)',
    'p': 'Basınç (hPa)',
    'rh': 'Bağıl Nem (%)',
    'wv': 'Rüzgar Hızı (m/s)',
    'rain': 'Yağış (mm)',
    'SWDR': 'Kısa Dalga Radyasyon (W/m²)',
    'PAR': 'FAR (μmol/m²s)'
}
stats_df['Açıklama'] = stats_df['Değişken'].map(var_descriptions)

print(stats_df.to_string(index=False))

# LaTeX formatında kaydet
latex_table1 = stats_df.to_latex(index=False, caption='Veri Seti Tanımlayıcı İstatistikleri',
                                  label='tab:descriptive_stats')
with open('table1_descriptive_stats.tex', 'w') as f:
    f.write(latex_table1)
print("\n✅ table1_descriptive_stats.tex kaydedildi")

print("=" * 70)
print("TABLO 2: EĞİTİM VE TEST SETİ BİLGİLERİ")
print("=" * 70)

dataset_info = pd.DataFrame({
    'Özellik': [
        'Toplam Gözlem (Ham)',
        'Toplam Gözlem (Saatlik)',
        'Eğitim Seti Gözlem',
        'Test Seti Gözlem',
        'Eğitim Başlangıç',
        'Eğitim Bitiş',
        'Test Başlangıç',
        'Test Bitiş',
        'Özellik Sayısı',
        'Test Periyodu'
    ],
    'Değer': [
        f"{len(df):,}",
        f"{len(df_hourly):,}",
        f"{len(train):,}",
        f"{len(test):,}",
        train['date'].min().strftime('%Y-%m-%d %H:%M'),
        train['date'].max().strftime('%Y-%m-%d %H:%M'),
        test['date'].min().strftime('%Y-%m-%d %H:%M'),
        test['date'].max().strftime('%Y-%m-%d %H:%M'),
        len(available_features),
        f"{TEST_DAYS} gün ({TEST_SIZE} saat)"
    ]
})

print(dataset_info.to_string(index=False))

dataset_info.to_csv('table2_dataset_info.csv', index=False)
print("\n✅ table2_dataset_info.csv kaydedildi")

print("=" * 70)
print("TABLO 3: MODEL PERFORMANS KARŞILAŞTIRMASI")
print("=" * 70)

# Detaylı metrikler hesapla
def detailed_metrics(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, y_pred)

    # MAPE (|T| > 1 için)
    mask = np.abs(y_true) > 1.0
    mape = np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100 if mask.sum() > 0 else np.nan

    # Max Error
    max_error = np.max(np.abs(y_true - y_pred))

    # Correlation
    corr = np.corrcoef(y_true, y_pred)[0, 1]

    return {
        'Model': model_name,
        'MAE (°C)': round(mae, 4),
        'RMSE (°C)': round(rmse, 4),
        'MSE': round(mse, 4),
        'R²': round(r2, 4),
        'MAPE (%)': round(mape, 2) if not np.isnan(mape) else '-',
        'Max Error (°C)': round(max_error, 2),
        'Pearson r': round(corr, 4)
    }

# Tüm modeller için hesapla
performance_results = []
for model_name, pred in all_predictions.items():
    metrics = detailed_metrics(y_test_actual, pred, model_name)
    performance_results.append(metrics)

performance_df = pd.DataFrame(performance_results)
performance_df = performance_df.sort_values('RMSE (°C)').reset_index(drop=True)

# Sıralama ekle
performance_df.insert(0, 'Sıra', range(1, len(performance_df) + 1))

print(performance_df.to_string(index=False))

# Kaydet
performance_df.to_csv('table3_model_performance.csv', index=False)
latex_table3 = performance_df.to_latex(index=False, caption='Model Performans Karşılaştırması',
                                        label='tab:model_performance')
with open('table3_model_performance.tex', 'w') as f:
    f.write(latex_table3)
print("\n✅ table3_model_performance.csv ve .tex kaydedildi")

print("=" * 70)
print("TABLO 4: ÖZELLİK ÖNEMLİLİK SIRALAMASI (TOP 15)")
print("=" * 70)

# Tüm modellerin importance değerlerini birleştir
importance_table = pd.DataFrame({'Özellik': available_features})
importance_table['Random Forest'] = rf_model.feature_importances_
importance_table['XGBoost'] = xgb_model.feature_importances_
importance_table['CatBoost'] = catboost_model.feature_importances_

# Normalize et (0-100 arası)
for col in ['Random Forest', 'XGBoost', 'CatBoost']:
    importance_table[col] = (importance_table[col] / importance_table[col].sum() * 100).round(2)

importance_table['Ortalama'] = importance_table[['Random Forest', 'XGBoost', 'CatBoost']].mean(axis=1).round(2)
importance_table = importance_table.sort_values('Ortalama', ascending=False).reset_index(drop=True)

# Sıra ekle
importance_table.insert(0, 'Sıra', range(1, len(importance_table) + 1))

# Özellik açıklamaları
feature_desc = {
    'T_lag_1': 't-1 Sıcaklık',
    'T_lag_2': 't-2 Sıcaklık',
    'T_lag_3': 't-3 Sıcaklık',
    'T_lag_6': 't-6 Sıcaklık',
    'T_lag_12': 't-12 Sıcaklık',
    'T_lag_24': 't-24 Sıcaklık',
    'T_rolling_6h_mean': '6 Saat Ort.',
    'T_rolling_24h_mean': '24 Saat Ort.',
    'T_rolling_6h_std': '6 Saat Std.',
    'hour': 'Saat',
    'hour_sin': 'Saat (sin)',
    'hour_cos': 'Saat (cos)',
    'month': 'Ay',
    'month_sin': 'Ay (sin)',
    'month_cos': 'Ay (cos)',
    'p': 'Basınç',
    'rh': 'Nem',
    'wv': 'Rüzgar Hızı',
    'SWDR': 'Radyasyon',
    'PAR': 'FAR'
}
importance_table['Açıklama'] = importance_table['Özellik'].map(feature_desc).fillna(importance_table['Özellik'])

print(importance_table.head(15).to_string(index=False))

importance_table.head(15).to_csv('table4_feature_importance.csv', index=False)
print("\n✅ table4_feature_importance.csv kaydedildi")

fig, axes = plt.subplots(3, 1, figsize=(14, 10), dpi=600)

# 1. All data
ax1 = axes[0]
ax1.plot(df_hourly['date'], df_hourly[TARGET], linewidth=0.5, color='#2C3E50', alpha=0.8)
ax1.axvline(x=test['date'].iloc[0], color='red', linestyle='--', linewidth=1.5, label='Train/Test Split')
ax1.set_title('(a) Temperature Time Series - Complete Dataset', fontweight='bold')
ax1.set_ylabel('Temperature (°C)')
ax1.legend(loc='upper right')

# 2. Monthly average and std
monthly = df_hourly.set_index('date').resample('M')[TARGET].agg(['mean', 'std']).reset_index()
ax2 = axes[1]
ax2.plot(monthly['date'], monthly['mean'], 'o-', color='#E74C3C', linewidth=2, markersize=6, label='Monthly Average')
ax2.fill_between(monthly['date'],
                  monthly['mean'] - monthly['std'],
                  monthly['mean'] + monthly['std'],
                  alpha=0.3, color='#E74C3C', label='±1 Std. Deviation')
ax2.set_title('(b) Monthly Temperature Trend', fontweight='bold')
ax2.set_ylabel('Temperature (°C)')
ax2.legend(loc='upper right')

# 3. Test period detail
ax3 = axes[2]
ax3.plot(test['date'], test[TARGET], linewidth=2, color='#2C3E50', label='Test Data')
ax3.set_title(f'(c) Test Period ({TEST_DAYS} Days)', fontweight='bold')
ax3.set_xlabel('Date')
ax3.set_ylabel('Temperature (°C)')
ax3.legend(loc='upper right')

plt.tight_layout()
plt.savefig('figure1_time_series_overview.png', dpi=300, bbox_inches='tight')
plt.savefig('figure1_time_series_overview.pdf', bbox_inches='tight')
plt.show()
print("✅ figure1_time_series_overview.png/pdf saved")

fig, axes = plt.subplots(2, 2, figsize=(14, 10), dpi=600)

# 1. Hourly pattern
ax1 = axes[0, 0]
hourly_stats = df_hourly.groupby('hour')[TARGET].agg(['mean', 'std'])
ax1.plot(hourly_stats.index, hourly_stats['mean'], 'o-', color='#3498DB', linewidth=2, markersize=8)
ax1.fill_between(hourly_stats.index,
                  hourly_stats['mean'] - hourly_stats['std'],
                  hourly_stats['mean'] + hourly_stats['std'],
                  alpha=0.3, color='#3498DB')
ax1.set_title('(a) Daily Temperature Cycle', fontweight='bold')
ax1.set_xlabel('Hour')
ax1.set_ylabel('Temperature (°C)')
ax1.set_xticks(range(0, 24, 2))

# 2. Monthly pattern
ax2 = axes[0, 1]
monthly_stats = df_hourly.groupby('month')[TARGET].agg(['mean', 'std'])
bars = ax2.bar(monthly_stats.index, monthly_stats['mean'], yerr=monthly_stats['std'],
               color='#E74C3C', alpha=0.7, capsize=3)
ax2.set_title('(b) Monthly Temperature Distribution', fontweight='bold')
ax2.set_xlabel('Month')
ax2.set_ylabel('Temperature (°C)')
ax2.set_xticks(range(1, 13))

# 3. Weekly pattern
ax3 = axes[1, 0]
daily_stats = df_hourly.groupby('dayofweek')[TARGET].agg(['mean', 'std'])
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
ax3.bar(range(7), daily_stats['mean'], yerr=daily_stats['std'],
        color='#2ECC71', alpha=0.7, capsize=3)
ax3.set_title('(c) Weekly Temperature Distribution', fontweight='bold')
ax3.set_xlabel('Day')
ax3.set_ylabel('Temperature (°C)')
ax3.set_xticks(range(7))
ax3.set_xticklabels(days)

# 4. Temperature distribution (histogram)
ax4 = axes[1, 1]
ax4.hist(df_hourly[TARGET], bins=50, color='#9B59B6', alpha=0.7, edgecolor='black', linewidth=0.5)
ax4.axvline(df_hourly[TARGET].mean(), color='red', linestyle='--', linewidth=2, label=f'Mean: {df_hourly[TARGET].mean():.1f}°C')
ax4.axvline(df_hourly[TARGET].median(), color='blue', linestyle=':', linewidth=2, label=f'Median: {df_hourly[TARGET].median():.1f}°C')
ax4.set_title('(d) Temperature Distribution', fontweight='bold')
ax4.set_xlabel('Temperature (°C)')
ax4.set_ylabel('Frequency')
ax4.legend()

plt.tight_layout()
plt.savefig('figure2_seasonality_analysis.png', dpi=300, bbox_inches='tight')
plt.savefig('figure2_seasonality_analysis.pdf', bbox_inches='tight')
plt.show()
print("✅ figure2_seasonality_analysis.png/pdf saved")

# Korelasyon için değişkenler
corr_vars = ['T', 'p', 'rh', 'wv', 'SWDR', 'PAR', 'rain',
             'T_lag_1', 'T_lag_6', 'T_lag_24', 'T_rolling_24h_mean']
corr_vars = [v for v in corr_vars if v in df_hourly.columns]

corr_matrix = df_hourly[corr_vars].corr()

# Variable labels
labels = {
    'T': 'Temperature',
    'p': 'Pressure',
    'rh': 'Humidity',
    'wv': 'Wind',
    'SWDR': 'Radiation',
    'PAR': 'PAR',
    'rain': 'Rain',
    'T_lag_1': 'T(t-1)',
    'T_lag_6': 'T(t-6)',
    'T_lag_24': 'T(t-24)',
    'T_rolling_24h_mean': 'T(24h Avg.)'
}

fig, ax = plt.subplots(figsize=(12, 10), dpi=600)
mask = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)

sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
            center=0, vmin=-1, vmax=1, square=True, linewidths=0.5,
            xticklabels=[labels.get(v, v) for v in corr_vars],
            yticklabels=[labels.get(v, v) for v in corr_vars],
            cbar_kws={'label': 'Pearson Correlation Coefficient'}, ax=ax)

ax.set_title('Correlation Matrix Between Variables', fontweight='bold', fontsize=14)
plt.tight_layout()
plt.savefig('figure3_correlation_matrix.png', dpi=300, bbox_inches='tight')
plt.savefig('figure3_correlation_matrix.pdf', bbox_inches='tight')
plt.show()
print("✅ figure3_correlation_matrix.png/pdf saved")

fig, axes = plt.subplots(2, 1, figsize=(14, 10), dpi=600)

# 1. All models
ax1 = axes[0]
ax1.plot(test_dates, y_test_actual, color='black', linewidth=2.5, label='Actual', zorder=10)

for model_name in ['Prophet', 'SARIMA', 'Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']:
    if model_name in all_predictions:
        ax1.plot(test_dates, all_predictions[model_name],
                 color=COLORS.get(model_name, 'gray'),
                 linewidth=1.5, alpha=0.7, label=model_name)

ax1.set_title('(a) All Model Predictions', fontweight='bold')
ax1.set_ylabel('Temperature (°C)')
ax1.legend(loc='upper right', ncol=4)
ax1.grid(True, alpha=0.3)

# 2. Only best ML models
ax2 = axes[1]
ax2.plot(test_dates, y_test_actual, color='black', linewidth=2.5, label='Actual', zorder=10)

best_models = ['Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']
for model_name in best_models:
    if model_name in all_predictions:
        ax2.plot(test_dates, all_predictions[model_name],
                 color=COLORS.get(model_name, 'gray'),
                 linewidth=1.8, alpha=0.8, label=model_name)

ax2.set_title('(b) ML Model Predictions (Detailed)', fontweight='bold')
ax2.set_xlabel('Date')
ax2.set_ylabel('Temperature (°C)')
ax2.legend(loc='upper right')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('figure4_model_predictions.png', dpi=300, bbox_inches='tight')
plt.savefig('figure4_model_predictions.pdf', bbox_inches='tight')
plt.show()
print("✅ figure4_model_predictions.png/pdf saved")

fig, axes = plt.subplots(2, 3, figsize=(15, 10), dpi=600)
axes = axes.flatten()

models_to_plot = ['Prophet', 'SARIMA', 'Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']

for idx, model_name in enumerate(models_to_plot):
    ax = axes[idx]

    if model_name in all_predictions:
        pred = all_predictions[model_name]

        # Scatter plot
        ax.scatter(y_test_actual, pred, alpha=0.6, color=COLORS.get(model_name, 'gray'), s=25, edgecolors='white', linewidth=0.5)

        # Perfect prediction line
        min_val = min(y_test_actual.min(), pred.min())
        max_val = max(y_test_actual.max(), pred.max())
        ax.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='Perfect Prediction')

        # Regression line
        slope, intercept, r_value, p_value, std_err = stats.linregress(y_test_actual, pred)
        line_x = np.array([min_val, max_val])
        line_y = slope * line_x + intercept
        ax.plot(line_x, line_y, 'b-', linewidth=1.5, alpha=0.7, label=f'Regression (r={r_value:.3f})')

        # Metrics
        r2 = r2_score(y_test_actual, pred)
        mae = mean_absolute_error(y_test_actual, pred)

        textstr = f'R² = {r2:.4f}\nMAE = {mae:.3f}°C'
        props = dict(boxstyle='round', facecolor='wheat', alpha=0.8)
        ax.text(0.05, 0.95, textstr, transform=ax.transAxes, fontsize=10,
                verticalalignment='top', bbox=props, fontweight='bold')

        ax.set_xlabel('Actual Temperature (°C)')
        ax.set_ylabel('Predicted Temperature (°C)')
        ax.set_title(f'({chr(97+idx)}) {model_name}', fontweight='bold')
        ax.legend(loc='lower right', fontsize=8)
        ax.set_aspect('equal', adjustable='box')

plt.tight_layout()
plt.savefig('figure5_scatter_plots.png', dpi=300, bbox_inches='tight')
plt.savefig('figure5_scatter_plots.pdf', bbox_inches='tight')
plt.show()
print("✅ figure5_scatter_plots.png/pdf saved")

fig, axes = plt.subplots(2, 3, figsize=(15, 10), dpi=300)
axes = axes.flatten()

models_to_plot = ['Prophet', 'SARIMA', 'Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']

for idx, model_name in enumerate(models_to_plot):
    ax = axes[idx]

    if model_name in all_predictions:
        pred = all_predictions[model_name]
        errors = y_test_actual - pred

        # Histogram
        n, bins, patches = ax.hist(errors, bins=30, color=COLORS.get(model_name, 'gray'),
                                    alpha=0.7, edgecolor='black', linewidth=0.5, density=True)

        # Normal distribution fit
        mu, std = stats.norm.fit(errors)
        x = np.linspace(errors.min(), errors.max(), 100)
        pdf = stats.norm.pdf(x, mu, std)
        ax.plot(x, pdf, 'r-', linewidth=2, label=f'Normal Fit\n(μ={mu:.2f}, σ={std:.2f})')

        # Zero line
        ax.axvline(x=0, color='black', linestyle='--', linewidth=1.5)
        ax.axvline(x=mu, color='blue', linestyle=':', linewidth=1.5, label=f'Mean: {mu:.3f}')

        # Shapiro-Wilk test (normality)
        if len(errors) <= 5000:
            shapiro_stat, shapiro_p = stats.shapiro(errors[:5000])
            normal_text = f'Shapiro p={shapiro_p:.4f}'
        else:
            normal_text = ''

        ax.set_xlabel('Prediction Error (°C)')
        ax.set_ylabel('Density')
        ax.set_title(f'({chr(97+idx)}) {model_name}', fontweight='bold')
        ax.legend(loc='upper right', fontsize=8)

plt.tight_layout()
plt.savefig('figure6_error_distributions.png', dpi=600, bbox_inches='tight')
plt.savefig('figure6_error_distributions.pdf', bbox_inches='tight')
plt.show()
print("✅ figure6_error_distributions.png/pdf saved")

fig, axes = plt.subplots(2, 2, figsize=(14, 10), dpi=600)

# Only sorted data
plot_df = performance_df.sort_values('RMSE (°C)')

# 1. MAE
ax1 = axes[0, 0]
colors_list = [COLORS.get(m, 'gray') for m in plot_df['Model']]
bars1 = ax1.barh(plot_df['Model'], plot_df['MAE (°C)'], color=colors_list, alpha=0.8, edgecolor='black')
ax1.set_xlabel('MAE (°C)')
ax1.set_title('(a) Mean Absolute Error (MAE)', fontweight='bold')
for i, (v, m) in enumerate(zip(plot_df['MAE (°C)'], plot_df['Model'])):
    ax1.text(v + 0.1, i, f'{v:.3f}', va='center', fontsize=10, fontweight='bold')

# 2. RMSE
ax2 = axes[0, 1]
bars2 = ax2.barh(plot_df['Model'], plot_df['RMSE (°C)'], color=colors_list, alpha=0.8, edgecolor='black')
ax2.set_xlabel('RMSE (°C)')
ax2.set_title('(b) Root Mean Square Error (RMSE)', fontweight='bold')
for i, v in enumerate(plot_df['RMSE (°C)']):
    ax2.text(v + 0.1, i, f'{v:.3f}', va='center', fontsize=10, fontweight='bold')

# 3. R²
ax3 = axes[1, 0]
r2_values = plot_df['R²'].values
bars3 = ax3.barh(plot_df['Model'], r2_values, color=colors_list, alpha=0.8, edgecolor='black')
ax3.set_xlabel('R²')
ax3.set_title('(c) Coefficient of Determination (R²)', fontweight='bold')
ax3.axvline(x=0, color='red', linestyle='--', linewidth=1)
for i, v in enumerate(r2_values):
    ax3.text(max(v, 0) + 0.02, i, f'{v:.4f}', va='center', fontsize=10, fontweight='bold')

# 4. Pearson r
ax4 = axes[1, 1]
pearson_values = plot_df['Pearson r'].values
bars4 = ax4.barh(plot_df['Model'], pearson_values, color=colors_list, alpha=0.8, edgecolor='black')
ax4.set_xlabel('Pearson r')
ax4.set_title('(d) Pearson Correlation Coefficient', fontweight='bold')
for i, v in enumerate(pearson_values):
    ax4.text(max(v, 0) + 0.02, i, f'{v:.4f}', va='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('figure7_performance_comparison.png', dpi=300, bbox_inches='tight')
plt.savefig('figure7_performance_comparison.pdf', bbox_inches='tight')
plt.show()
print("✅ figure7_performance_comparison.png/pdf saved")

fig, axes = plt.subplots(1, 2, figsize=(14, 8), dpi=600)

# Top 15 features
top_n = 15
top_features = importance_table.head(top_n)

# 1. Grouped bar chart
ax1 = axes[0]
x = np.arange(top_n)
width = 0.25

bars1 = ax1.barh(x - width, top_features['Random Forest'], width, label='Random Forest',
                  color=COLORS['Random Forest'], alpha=0.8)
bars2 = ax1.barh(x, top_features['XGBoost'], width, label='XGBoost',
                  color=COLORS['XGBoost'], alpha=0.8)
bars3 = ax1.barh(x + width, top_features['CatBoost'], width, label='CatBoost',
                  color=COLORS['CatBoost'], alpha=0.8)

ax1.set_yticks(x)
ax1.set_yticklabels(top_features['Özellik'])
ax1.invert_yaxis()
ax1.set_xlabel('Importance Score (%)')
ax1.set_title('(a) Model-Based Feature Importance', fontweight='bold')
ax1.legend(loc='lower right')

# 2. Average importance
ax2 = axes[1]
colors_feat = ['#E74C3C' if 'T_lag' in f or 'T_rolling' in f else '#3498DB' for f in top_features['Özellik']]
bars = ax2.barh(top_features['Özellik'], top_features['Ortalama'], color=colors_feat, alpha=0.8, edgecolor='black')
ax2.invert_yaxis()
ax2.set_xlabel('Average Importance Score (%)')
ax2.set_title('(b) Average Feature Importance', fontweight='bold')

# Add values
for i, v in enumerate(top_features['Ortalama']):
    ax2.text(v + 0.3, i, f'{v:.1f}%', va='center', fontsize=9)

# Legend for colors
from matplotlib.patches import Patch
legend_elements = [Patch(facecolor='#E74C3C', label='Lag/Rolling Features'),
                   Patch(facecolor='#3498DB', label='Other Features')]
ax2.legend(handles=legend_elements, loc='lower right')

plt.tight_layout()
plt.savefig('figure8_feature_importance.png', dpi=300, bbox_inches='tight')
plt.savefig('figure8_feature_importance.pdf', bbox_inches='tight')
plt.show()
print("✅ figure8_feature_importance.png/pdf saved")

# Error analysis with test data
test_with_errors = pd.DataFrame({
    'date': test_dates,
    'hour': test['hour'].values,
    'actual': y_test_actual
})

for model_name, pred in all_predictions.items():
    test_with_errors[f'{model_name}_error'] = y_test_actual - pred
    test_with_errors[f'{model_name}_abs_error'] = np.abs(y_test_actual - pred)

fig, axes = plt.subplots(2, 2, figsize=(14, 10), dpi=300)

# 1. Hourly MAE - ML models
ax1 = axes[0, 0]
ml_models = ['Random Forest', 'XGBoost', 'CatBoost', 'Hybrid']
for model in ml_models:
    hourly_mae = test_with_errors.groupby('hour')[f'{model}_abs_error'].mean()
    ax1.plot(hourly_mae.index, hourly_mae.values, 'o-', label=model,
             color=COLORS.get(model, 'gray'), linewidth=2, markersize=6)

ax1.set_xlabel('Hour')
ax1.set_ylabel('MAE (°C)')
ax1.set_title('(a) Hourly Mean Absolute Error', fontweight='bold')
ax1.set_xticks(range(0, 24, 2))
ax1.legend()
ax1.grid(True, alpha=0.3)

# 2. Box plot - hourly errors (Hybrid)
ax2 = axes[0, 1]
hourly_errors_hybrid = [test_with_errors[test_with_errors['hour'] == h]['Hybrid_error'].values
                        for h in range(24)]
bp = ax2.boxplot(hourly_errors_hybrid, positions=range(24), widths=0.6, patch_artist=True)
for patch in bp['boxes']:
    patch.set_facecolor(COLORS['Hybrid'])
    patch.set_alpha(0.6)
ax2.axhline(y=0, color='red', linestyle='--', linewidth=1)
ax2.set_xlabel('Hour')
ax2.set_ylabel('Prediction Error (°C)')
ax2.set_title('(b) Hourly Error Distribution (Hybrid Model)', fontweight='bold')
ax2.set_xticks(range(0, 24, 2))

# 3. Error time series
ax3 = axes[1, 0]
for model in ['Random Forest', 'Hybrid']:
    ax3.plot(test_dates, test_with_errors[f'{model}_error'],
             label=model, color=COLORS.get(model, 'gray'), alpha=0.7, linewidth=1)
ax3.axhline(y=0, color='red', linestyle='--', linewidth=1.5)
ax3.set_xlabel('Date')
ax3.set_ylabel('Prediction Error (°C)')
ax3.set_title('(c) Error Time Series', fontweight='bold')
ax3.legend()

# 4. Cumulative error
ax4 = axes[1, 1]
for model in ml_models:
    cumulative_mae = test_with_errors[f'{model}_abs_error'].expanding().mean()
    ax4.plot(test_dates, cumulative_mae, label=model,
             color=COLORS.get(model, 'gray'), linewidth=2)

ax4.set_xlabel('Date')
ax4.set_ylabel('Cumulative MAE (°C)')
ax4.set_title('(d) Cumulative Mean Absolute Error', fontweight='bold')
ax4.legend()

plt.tight_layout()
plt.savefig('figure9_hourly_error_analysis.png', dpi=300, bbox_inches='tight')
plt.savefig('figure9_hourly_error_analysis.pdf', bbox_inches='tight')
plt.show()
print("✅ figure9_hourly_error_analysis.png/pdf saved")

# Best model (Hybrid)
best_model_name = 'Hybrid'
best_pred = all_predictions[best_model_name]

fig, axes = plt.subplots(2, 2, figsize=(14, 10), dpi=600)

# 1. Prediction vs Actual (detailed)
ax1 = axes[0, 0]
ax1.plot(test_dates, y_test_actual, 'b-', linewidth=2, label='Actual', zorder=5)
ax1.plot(test_dates, best_pred, 'r--', linewidth=2, label='Prediction', zorder=4)
ax1.fill_between(test_dates, y_test_actual, best_pred, alpha=0.3, color='gray', label='Error Area')
ax1.set_xlabel('Date')
ax1.set_ylabel('Temperature (°C)')
ax1.set_title(f'(a) {best_model_name} - Actual vs Prediction', fontweight='bold')
ax1.legend()

# 2. Scatter plot (large)
ax2 = axes[0, 1]
ax2.scatter(y_test_actual, best_pred, alpha=0.6, color=COLORS[best_model_name], s=40, edgecolors='white')
min_val, max_val = min(y_test_actual.min(), best_pred.min()), max(y_test_actual.max(), best_pred.max())
ax2.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='y = x')

# Regression
slope, intercept, r_value, _, _ = stats.linregress(y_test_actual, best_pred)
line_x = np.array([min_val, max_val])
ax2.plot(line_x, slope * line_x + intercept, 'b-', linewidth=1.5,
         label=f'Regression: y = {slope:.3f}x + {intercept:.3f}')

r2 = r2_score(y_test_actual, best_pred)
mae = mean_absolute_error(y_test_actual, best_pred)
rmse = np.sqrt(mean_squared_error(y_test_actual, best_pred))

textstr = f'R² = {r2:.4f}\nMAE = {mae:.4f}°C\nRMSE = {rmse:.4f}°C'
ax2.text(0.05, 0.95, textstr, transform=ax2.transAxes, fontsize=11, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8), fontweight='bold')

ax2.set_xlabel('Actual Temperature (°C)')
ax2.set_ylabel('Predicted Temperature (°C)')
ax2.set_title(f'(b) {best_model_name} - Scatter Plot', fontweight='bold')
ax2.legend(loc='lower right')
ax2.set_aspect('equal', adjustable='box')

# 3. Residual plot
ax3 = axes[1, 0]
errors = y_test_actual - best_pred
ax3.scatter(best_pred, errors, alpha=0.6, color=COLORS[best_model_name], s=30)
ax3.axhline(y=0, color='red', linestyle='--', linewidth=2)
ax3.axhline(y=errors.mean(), color='blue', linestyle=':', linewidth=1.5,
            label=f'Mean: {errors.mean():.4f}')
ax3.axhline(y=errors.mean() + 2*errors.std(), color='gray', linestyle='--', alpha=0.5)
ax3.axhline(y=errors.mean() - 2*errors.std(), color='gray', linestyle='--', alpha=0.5,
            label=f'±2σ: {2*errors.std():.3f}')
ax3.set_xlabel('Predicted Temperature (°C)')
ax3.set_ylabel('Residual (°C)')
ax3.set_title(f'(c) {best_model_name} - Residual Analysis', fontweight='bold')
ax3.legend()

# 4. Q-Q Plot
ax4 = axes[1, 1]
stats.probplot(errors, dist="norm", plot=ax4)
ax4.set_title(f'(d) {best_model_name} - Q-Q Plot (Normality)', fontweight='bold')
ax4.get_lines()[0].set_markerfacecolor(COLORS[best_model_name])
ax4.get_lines()[0].set_markersize(5)

plt.tight_layout()
plt.savefig('figure10_best_model_analysis.png', dpi=300, bbox_inches='tight')
plt.savefig('figure10_best_model_analysis.pdf', bbox_inches='tight')
plt.show()
print("✅ figure10_best_model_analysis.png/pdf saved")

print("=" * 70)
print("TABLO 5: İSTATİSTİKSEL TEST SONUÇLARI")
print("=" * 70)

statistical_tests = []

for model_name, pred in all_predictions.items():
    errors = y_test_actual - pred

    # Normallik testi (Shapiro-Wilk)
    if len(errors) > 5000:
        shapiro_stat, shapiro_p = stats.shapiro(errors[:5000])
    else:
        shapiro_stat, shapiro_p = stats.shapiro(errors)

    # Durbin-Watson (otokorelasyon)
    from statsmodels.stats.stattools import durbin_watson
    dw_stat = durbin_watson(errors)

    # Mean ve Std
    mean_err = errors.mean()
    std_err = errors.std()

    # Skewness ve Kurtosis
    skew = stats.skew(errors)
    kurt = stats.kurtosis(errors)

    statistical_tests.append({
        'Model': model_name,
        'Hata Ort.': round(mean_err, 4),
        'Hata Std.': round(std_err, 4),
        'Çarpıklık': round(skew, 4),
        'Basıklık': round(kurt, 4),
        'Shapiro W': round(shapiro_stat, 4),
        'Shapiro p': round(shapiro_p, 4),
        'Durbin-Watson': round(dw_stat, 4)
    })

stats_test_df = pd.DataFrame(statistical_tests)
stats_test_df = stats_test_df.sort_values('Hata Std.').reset_index(drop=True)

print(stats_test_df.to_string(index=False))

stats_test_df.to_csv('table5_statistical_tests.csv', index=False)
print("\n✅ table5_statistical_tests.csv kaydedildi")

print("\n📊 Yorum:")
print("• Durbin-Watson ≈ 2: Otokorelasyon yok (ideal)")
print("• Durbin-Watson < 1.5: Pozitif otokorelasyon var")
print("• Shapiro p > 0.05: Hatalar normal dağılımlı")

print("=" * 70)
print("TABLO 6: MODEL KARMAŞIKLIK KARŞILAŞTIRMASI")
print("=" * 70)

model_complexity = pd.DataFrame({
    'Model': ['Prophet', 'SARIMA', 'Random Forest', 'XGBoost', 'CatBoost', 'Hybrid (Stacking)'],
    'Tip': ['Aditif', 'ARIMA', 'Ensemble', 'Boosting', 'Boosting', 'Stacking'],
    'Parametre Sayısı': ['~20', '~10', '~200 ağaç', '~300 ağaç', '~500 iter', '~3 model'],
    'Eğitim Süresi': ['Orta', 'Yüksek', 'Düşük', 'Düşük', 'Düşük', 'Yüksek'],
    'Yorumlanabilirlik': ['Yüksek', 'Orta', 'Orta', 'Düşük', 'Düşük', 'Düşük'],
    'Lag Feature Kullanımı': ['Hayır', 'Otomatik', 'Evet', 'Evet', 'Evet', 'Evet'],
    'Exogenous Değişken': ['Evet', 'Sınırlı', 'Evet', 'Evet', 'Evet', 'Evet']
})

print(model_complexity.to_string(index=False))

model_complexity.to_csv('table6_model_complexity.csv', index=False)
print("\n✅ table6_model_complexity.csv kaydedildi")

print("=" * 70)
print("📁 OLUŞTURULAN DOSYALAR")
print("=" * 70)

import os

files_created = {
    'Tablolar (CSV)': [
        'table1_descriptive_stats.tex',
        'table2_dataset_info.csv',
        'table3_model_performance.csv',
        'table4_feature_importance.csv',
        'table5_statistical_tests.csv',
        'table6_model_complexity.csv'
    ],
    'Şekiller (PNG/PDF)': [
        'figure1_time_series_overview',
        'figure2_seasonality_analysis',
        'figure3_correlation_matrix',
        'figure4_model_predictions',
        'figure5_scatter_plots',
        'figure6_error_distributions',
        'figure7_performance_comparison',
        'figure8_feature_importance',
        'figure9_hourly_error_analysis',
        'figure10_best_model_analysis'
    ]
}

for category, files in files_created.items():
    print(f"\n📂 {category}:")
    for f in files:
        if category == 'Şekiller (PNG/PDF)':
            print(f"   • {f}.png")
            print(f"   • {f}.pdf")
        else:
            print(f"   • {f}")

print("\n" + "=" * 70)
print("✅ Tüm akademik içerik oluşturuldu!")
print("=" * 70)

print("=" * 70)
print("📝 AKADEMİK MAKALE ÖZET METNİ")
print("=" * 70)

best_r2 = performance_df.iloc[0]['R²']
best_mae = performance_df.iloc[0]['MAE (°C)']
best_rmse = performance_df.iloc[0]['RMSE (°C)']
best_model = performance_df.iloc[0]['Model']

abstract = f"""
ÖZET

Bu çalışmada, saatlik sıcaklık tahmini için farklı makine öğrenmesi ve
zaman serisi modellerinin karşılaştırmalı analizi gerçekleştirilmiştir.
Çalışmada {len(df):,} adet 10 dakikalık meteorolojik gözlem verisi kullanılmış
ve bu veriler saatlik ortalamalara dönüştürülerek {len(df_hourly):,} gözlem
elde edilmiştir.

Altı farklı tahmin modeli değerlendirilmiştir: Prophet, SARIMA,
Random Forest, XGBoost, CatBoost ve Hibrit Stacking Ensemble.
Model performansları MAE, RMSE, R² ve MAPE metrikleri ile ölçülmüştür.

Sonuçlar, {best_model} modelinin en yüksek performansı sergilediğini
göstermiştir (R² = {best_r2}, MAE = {best_mae}°C, RMSE = {best_rmse}°C).
Lag özellikleri (t-1, t-6, t-24 sıcaklık değerleri) ve hareketli ortalamalar
model performansını önemli ölçüde artırmıştır. Özellik önemliliği analizi,
T_lag_1 (bir saat önceki sıcaklık) değişkeninin en belirleyici faktör
olduğunu ortaya koymuştur.

Geleneksel zaman serisi modelleri (Prophet, SARIMA) 7 günlük tahmin
horizonunda makine öğrenmesi modellerine kıyasla düşük performans
göstermiştir. Bu durum, lag özelliklerinin doğrudan kullanılamamasından
kaynaklanmaktadır.

Anahtar Kelimeler: Sıcaklık tahmini, makine öğrenmesi, zaman serisi,
ensemble learning, meteorolojik tahmin

---

ABSTRACT

This study presents a comparative analysis of various machine learning
and time series models for hourly temperature forecasting. The dataset
comprises {len(df):,} observations at 10-minute intervals, aggregated
into {len(df_hourly):,} hourly observations.

Six prediction models were evaluated: Prophet, SARIMA, Random Forest,
XGBoost, CatBoost, and Hybrid Stacking Ensemble. Model performance was
assessed using MAE, RMSE, R², and MAPE metrics.

Results indicate that the {best_model} model achieved the highest
performance (R² = {best_r2}, MAE = {best_mae}°C, RMSE = {best_rmse}°C).
Lag features (t-1, t-6, t-24 temperature values) and rolling averages
significantly improved model performance. Feature importance analysis
revealed that T_lag_1 (previous hour temperature) was the most
influential predictor.

Traditional time series models (Prophet, SARIMA) exhibited lower
performance compared to machine learning models for the 7-day forecast
horizon, primarily due to their inability to directly utilize lag features.

Keywords: Temperature forecasting, machine learning, time series,
ensemble learning, meteorological prediction
"""

print(abstract)

# Kaydet
with open('abstract_summary.txt', 'w', encoding='utf-8') as f:
    f.write(abstract)
print("\n✅ abstract_summary.txt kaydedildi")

